#!/bin/bash

# Define the key name
KEY_NAME="school"

# Define the number of bits for the key
BITS=4096

# Define the passphrase
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -f $KEY_NAME -N $PASSPHRASE

